version: '3'

services:
  user:
    image: docker.io/library/user-service-api:latest
    ports:
      - "8080:8080"
    networks:
      - moveinsync

  admin:
    image: docker.io/library/admin-service-api:latest
    ports:
      - "8081:8081"
    networks:
      - moveinsync

  cab-data:
    image: docker.io/library/cab-data-service:latest
    ports:
      - "8082:8082"
    networks:
      - moveinsync

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports: 
      - "9090:9090"
    networks:
      - moveinsync
    depends_on:
      - user
      - admin
      - cab-data

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - moveinsync
    depends_on:
      - prometheus

volumes:
  grafana-data:

networks:
  moveinsync: