version: '3'

services:
  admin:
    image: docker.io/library/admin-service-api:latest
    ports:
      - "8081:8081"
    networks:
      - moveinsync
  user:
    image: docker.io/library/user-service-api:latest
    ports:
      - "8080:8080"
    networks:
      - moveinsync
  
networks:
  moveinsync: