{
 "title": "MoveInSync",
 "description": "Dashboard for MoveInSync Case Study: Smart Cab Allocation.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Percentage up-time over the last 24 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(up[24h]) * 100", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of HTTP requests ",
   "type": "bargauge",
   "description": "Total number of HTTP requests in the last 'x' hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gin_gin_request_size_bytes_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average response time of HTTP endpoints",
   "type": "timeseries",
   "description": "Rolling average response time of HTTP endpoints over the last 1 hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(gin_gin_request_duration_sum[1h])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Rate of byte allocation",
   "type": "stat",
   "description": "Average rate of bytes allocated, even if freed over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}